# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/andreas/uni/AdvPT/Project/sc2-simulation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/andreas/uni/AdvPT/Project/sc2-simulation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andreas/uni/AdvPT/Project/sc2-simulation/CMakeFiles /home/andreas/uni/AdvPT/Project/sc2-simulation/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andreas/uni/AdvPT/Project/sc2-simulation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named starcraft

# Build rule for target.
starcraft: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 starcraft
.PHONY : starcraft

# fast build rule for target.
starcraft/fast:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/build
.PHONY : starcraft/fast

src/Building.o: src/Building.cpp.o

.PHONY : src/Building.o

# target to build an object file
src/Building.cpp.o:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/Building.cpp.o
.PHONY : src/Building.cpp.o

src/Building.i: src/Building.cpp.i

.PHONY : src/Building.i

# target to preprocess a source file
src/Building.cpp.i:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/Building.cpp.i
.PHONY : src/Building.cpp.i

src/Building.s: src/Building.cpp.s

.PHONY : src/Building.s

# target to generate assembly for a file
src/Building.cpp.s:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/Building.cpp.s
.PHONY : src/Building.cpp.s

src/BuildlistValidator.o: src/BuildlistValidator.cpp.o

.PHONY : src/BuildlistValidator.o

# target to build an object file
src/BuildlistValidator.cpp.o:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/BuildlistValidator.cpp.o
.PHONY : src/BuildlistValidator.cpp.o

src/BuildlistValidator.i: src/BuildlistValidator.cpp.i

.PHONY : src/BuildlistValidator.i

# target to preprocess a source file
src/BuildlistValidator.cpp.i:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/BuildlistValidator.cpp.i
.PHONY : src/BuildlistValidator.cpp.i

src/BuildlistValidator.s: src/BuildlistValidator.cpp.s

.PHONY : src/BuildlistValidator.s

# target to generate assembly for a file
src/BuildlistValidator.cpp.s:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/BuildlistValidator.cpp.s
.PHONY : src/BuildlistValidator.cpp.s

src/CSVParser.o: src/CSVParser.cpp.o

.PHONY : src/CSVParser.o

# target to build an object file
src/CSVParser.cpp.o:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/CSVParser.cpp.o
.PHONY : src/CSVParser.cpp.o

src/CSVParser.i: src/CSVParser.cpp.i

.PHONY : src/CSVParser.i

# target to preprocess a source file
src/CSVParser.cpp.i:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/CSVParser.cpp.i
.PHONY : src/CSVParser.cpp.i

src/CSVParser.s: src/CSVParser.cpp.s

.PHONY : src/CSVParser.s

# target to generate assembly for a file
src/CSVParser.cpp.s:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/CSVParser.cpp.s
.PHONY : src/CSVParser.cpp.s

src/Entity.o: src/Entity.cpp.o

.PHONY : src/Entity.o

# target to build an object file
src/Entity.cpp.o:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/Entity.cpp.o
.PHONY : src/Entity.cpp.o

src/Entity.i: src/Entity.cpp.i

.PHONY : src/Entity.i

# target to preprocess a source file
src/Entity.cpp.i:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/Entity.cpp.i
.PHONY : src/Entity.cpp.i

src/Entity.s: src/Entity.cpp.s

.PHONY : src/Entity.s

# target to generate assembly for a file
src/Entity.cpp.s:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/Entity.cpp.s
.PHONY : src/Entity.cpp.s

src/EntityData.o: src/EntityData.cpp.o

.PHONY : src/EntityData.o

# target to build an object file
src/EntityData.cpp.o:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/EntityData.cpp.o
.PHONY : src/EntityData.cpp.o

src/EntityData.i: src/EntityData.cpp.i

.PHONY : src/EntityData.i

# target to preprocess a source file
src/EntityData.cpp.i:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/EntityData.cpp.i
.PHONY : src/EntityData.cpp.i

src/EntityData.s: src/EntityData.cpp.s

.PHONY : src/EntityData.s

# target to generate assembly for a file
src/EntityData.cpp.s:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/EntityData.cpp.s
.PHONY : src/EntityData.cpp.s

src/FixedPoint.o: src/FixedPoint.cpp.o

.PHONY : src/FixedPoint.o

# target to build an object file
src/FixedPoint.cpp.o:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/FixedPoint.cpp.o
.PHONY : src/FixedPoint.cpp.o

src/FixedPoint.i: src/FixedPoint.cpp.i

.PHONY : src/FixedPoint.i

# target to preprocess a source file
src/FixedPoint.cpp.i:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/FixedPoint.cpp.i
.PHONY : src/FixedPoint.cpp.i

src/FixedPoint.s: src/FixedPoint.cpp.s

.PHONY : src/FixedPoint.s

# target to generate assembly for a file
src/FixedPoint.cpp.s:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/FixedPoint.cpp.s
.PHONY : src/FixedPoint.cpp.s

src/JsonLogger.o: src/JsonLogger.cpp.o

.PHONY : src/JsonLogger.o

# target to build an object file
src/JsonLogger.cpp.o:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/JsonLogger.cpp.o
.PHONY : src/JsonLogger.cpp.o

src/JsonLogger.i: src/JsonLogger.cpp.i

.PHONY : src/JsonLogger.i

# target to preprocess a source file
src/JsonLogger.cpp.i:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/JsonLogger.cpp.i
.PHONY : src/JsonLogger.cpp.i

src/JsonLogger.s: src/JsonLogger.cpp.s

.PHONY : src/JsonLogger.s

# target to generate assembly for a file
src/JsonLogger.cpp.s:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/JsonLogger.cpp.s
.PHONY : src/JsonLogger.cpp.s

src/JsonLoggerV2.o: src/JsonLoggerV2.cpp.o

.PHONY : src/JsonLoggerV2.o

# target to build an object file
src/JsonLoggerV2.cpp.o:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/JsonLoggerV2.cpp.o
.PHONY : src/JsonLoggerV2.cpp.o

src/JsonLoggerV2.i: src/JsonLoggerV2.cpp.i

.PHONY : src/JsonLoggerV2.i

# target to preprocess a source file
src/JsonLoggerV2.cpp.i:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/JsonLoggerV2.cpp.i
.PHONY : src/JsonLoggerV2.cpp.i

src/JsonLoggerV2.s: src/JsonLoggerV2.cpp.s

.PHONY : src/JsonLoggerV2.s

# target to generate assembly for a file
src/JsonLoggerV2.cpp.s:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/JsonLoggerV2.cpp.s
.PHONY : src/JsonLoggerV2.cpp.s

src/ProtossBuilding.o: src/ProtossBuilding.cpp.o

.PHONY : src/ProtossBuilding.o

# target to build an object file
src/ProtossBuilding.cpp.o:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/ProtossBuilding.cpp.o
.PHONY : src/ProtossBuilding.cpp.o

src/ProtossBuilding.i: src/ProtossBuilding.cpp.i

.PHONY : src/ProtossBuilding.i

# target to preprocess a source file
src/ProtossBuilding.cpp.i:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/ProtossBuilding.cpp.i
.PHONY : src/ProtossBuilding.cpp.i

src/ProtossBuilding.s: src/ProtossBuilding.cpp.s

.PHONY : src/ProtossBuilding.s

# target to generate assembly for a file
src/ProtossBuilding.cpp.s:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/ProtossBuilding.cpp.s
.PHONY : src/ProtossBuilding.cpp.s

src/ProtossSimulator.o: src/ProtossSimulator.cpp.o

.PHONY : src/ProtossSimulator.o

# target to build an object file
src/ProtossSimulator.cpp.o:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/ProtossSimulator.cpp.o
.PHONY : src/ProtossSimulator.cpp.o

src/ProtossSimulator.i: src/ProtossSimulator.cpp.i

.PHONY : src/ProtossSimulator.i

# target to preprocess a source file
src/ProtossSimulator.cpp.i:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/ProtossSimulator.cpp.i
.PHONY : src/ProtossSimulator.cpp.i

src/ProtossSimulator.s: src/ProtossSimulator.cpp.s

.PHONY : src/ProtossSimulator.s

# target to generate assembly for a file
src/ProtossSimulator.cpp.s:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/ProtossSimulator.cpp.s
.PHONY : src/ProtossSimulator.cpp.s

src/ProtossUnit.o: src/ProtossUnit.cpp.o

.PHONY : src/ProtossUnit.o

# target to build an object file
src/ProtossUnit.cpp.o:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/ProtossUnit.cpp.o
.PHONY : src/ProtossUnit.cpp.o

src/ProtossUnit.i: src/ProtossUnit.cpp.i

.PHONY : src/ProtossUnit.i

# target to preprocess a source file
src/ProtossUnit.cpp.i:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/ProtossUnit.cpp.i
.PHONY : src/ProtossUnit.cpp.i

src/ProtossUnit.s: src/ProtossUnit.cpp.s

.PHONY : src/ProtossUnit.s

# target to generate assembly for a file
src/ProtossUnit.cpp.s:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/ProtossUnit.cpp.s
.PHONY : src/ProtossUnit.cpp.s

src/ResourceManager.o: src/ResourceManager.cpp.o

.PHONY : src/ResourceManager.o

# target to build an object file
src/ResourceManager.cpp.o:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/ResourceManager.cpp.o
.PHONY : src/ResourceManager.cpp.o

src/ResourceManager.i: src/ResourceManager.cpp.i

.PHONY : src/ResourceManager.i

# target to preprocess a source file
src/ResourceManager.cpp.i:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/ResourceManager.cpp.i
.PHONY : src/ResourceManager.cpp.i

src/ResourceManager.s: src/ResourceManager.cpp.s

.PHONY : src/ResourceManager.s

# target to generate assembly for a file
src/ResourceManager.cpp.s:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/ResourceManager.cpp.s
.PHONY : src/ResourceManager.cpp.s

src/Tech.o: src/Tech.cpp.o

.PHONY : src/Tech.o

# target to build an object file
src/Tech.cpp.o:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/Tech.cpp.o
.PHONY : src/Tech.cpp.o

src/Tech.i: src/Tech.cpp.i

.PHONY : src/Tech.i

# target to preprocess a source file
src/Tech.cpp.i:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/Tech.cpp.i
.PHONY : src/Tech.cpp.i

src/Tech.s: src/Tech.cpp.s

.PHONY : src/Tech.s

# target to generate assembly for a file
src/Tech.cpp.s:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/Tech.cpp.s
.PHONY : src/Tech.cpp.s

src/TerranBuilding.o: src/TerranBuilding.cpp.o

.PHONY : src/TerranBuilding.o

# target to build an object file
src/TerranBuilding.cpp.o:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/TerranBuilding.cpp.o
.PHONY : src/TerranBuilding.cpp.o

src/TerranBuilding.i: src/TerranBuilding.cpp.i

.PHONY : src/TerranBuilding.i

# target to preprocess a source file
src/TerranBuilding.cpp.i:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/TerranBuilding.cpp.i
.PHONY : src/TerranBuilding.cpp.i

src/TerranBuilding.s: src/TerranBuilding.cpp.s

.PHONY : src/TerranBuilding.s

# target to generate assembly for a file
src/TerranBuilding.cpp.s:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/TerranBuilding.cpp.s
.PHONY : src/TerranBuilding.cpp.s

src/TerranSimulator.o: src/TerranSimulator.cpp.o

.PHONY : src/TerranSimulator.o

# target to build an object file
src/TerranSimulator.cpp.o:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/TerranSimulator.cpp.o
.PHONY : src/TerranSimulator.cpp.o

src/TerranSimulator.i: src/TerranSimulator.cpp.i

.PHONY : src/TerranSimulator.i

# target to preprocess a source file
src/TerranSimulator.cpp.i:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/TerranSimulator.cpp.i
.PHONY : src/TerranSimulator.cpp.i

src/TerranSimulator.s: src/TerranSimulator.cpp.s

.PHONY : src/TerranSimulator.s

# target to generate assembly for a file
src/TerranSimulator.cpp.s:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/TerranSimulator.cpp.s
.PHONY : src/TerranSimulator.cpp.s

src/TerranUnit.o: src/TerranUnit.cpp.o

.PHONY : src/TerranUnit.o

# target to build an object file
src/TerranUnit.cpp.o:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/TerranUnit.cpp.o
.PHONY : src/TerranUnit.cpp.o

src/TerranUnit.i: src/TerranUnit.cpp.i

.PHONY : src/TerranUnit.i

# target to preprocess a source file
src/TerranUnit.cpp.i:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/TerranUnit.cpp.i
.PHONY : src/TerranUnit.cpp.i

src/TerranUnit.s: src/TerranUnit.cpp.s

.PHONY : src/TerranUnit.s

# target to generate assembly for a file
src/TerranUnit.cpp.s:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/TerranUnit.cpp.s
.PHONY : src/TerranUnit.cpp.s

src/Timer.o: src/Timer.cpp.o

.PHONY : src/Timer.o

# target to build an object file
src/Timer.cpp.o:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/Timer.cpp.o
.PHONY : src/Timer.cpp.o

src/Timer.i: src/Timer.cpp.i

.PHONY : src/Timer.i

# target to preprocess a source file
src/Timer.cpp.i:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/Timer.cpp.i
.PHONY : src/Timer.cpp.i

src/Timer.s: src/Timer.cpp.s

.PHONY : src/Timer.s

# target to generate assembly for a file
src/Timer.cpp.s:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/Timer.cpp.s
.PHONY : src/Timer.cpp.s

src/Unit.o: src/Unit.cpp.o

.PHONY : src/Unit.o

# target to build an object file
src/Unit.cpp.o:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/Unit.cpp.o
.PHONY : src/Unit.cpp.o

src/Unit.i: src/Unit.cpp.i

.PHONY : src/Unit.i

# target to preprocess a source file
src/Unit.cpp.i:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/Unit.cpp.i
.PHONY : src/Unit.cpp.i

src/Unit.s: src/Unit.cpp.s

.PHONY : src/Unit.s

# target to generate assembly for a file
src/Unit.cpp.s:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/Unit.cpp.s
.PHONY : src/Unit.cpp.s

src/ZergBuilding.o: src/ZergBuilding.cpp.o

.PHONY : src/ZergBuilding.o

# target to build an object file
src/ZergBuilding.cpp.o:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/ZergBuilding.cpp.o
.PHONY : src/ZergBuilding.cpp.o

src/ZergBuilding.i: src/ZergBuilding.cpp.i

.PHONY : src/ZergBuilding.i

# target to preprocess a source file
src/ZergBuilding.cpp.i:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/ZergBuilding.cpp.i
.PHONY : src/ZergBuilding.cpp.i

src/ZergBuilding.s: src/ZergBuilding.cpp.s

.PHONY : src/ZergBuilding.s

# target to generate assembly for a file
src/ZergBuilding.cpp.s:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/ZergBuilding.cpp.s
.PHONY : src/ZergBuilding.cpp.s

src/ZergSimulator.o: src/ZergSimulator.cpp.o

.PHONY : src/ZergSimulator.o

# target to build an object file
src/ZergSimulator.cpp.o:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/ZergSimulator.cpp.o
.PHONY : src/ZergSimulator.cpp.o

src/ZergSimulator.i: src/ZergSimulator.cpp.i

.PHONY : src/ZergSimulator.i

# target to preprocess a source file
src/ZergSimulator.cpp.i:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/ZergSimulator.cpp.i
.PHONY : src/ZergSimulator.cpp.i

src/ZergSimulator.s: src/ZergSimulator.cpp.s

.PHONY : src/ZergSimulator.s

# target to generate assembly for a file
src/ZergSimulator.cpp.s:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/ZergSimulator.cpp.s
.PHONY : src/ZergSimulator.cpp.s

src/ZergUnit.o: src/ZergUnit.cpp.o

.PHONY : src/ZergUnit.o

# target to build an object file
src/ZergUnit.cpp.o:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/ZergUnit.cpp.o
.PHONY : src/ZergUnit.cpp.o

src/ZergUnit.i: src/ZergUnit.cpp.i

.PHONY : src/ZergUnit.i

# target to preprocess a source file
src/ZergUnit.cpp.i:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/ZergUnit.cpp.i
.PHONY : src/ZergUnit.cpp.i

src/ZergUnit.s: src/ZergUnit.cpp.s

.PHONY : src/ZergUnit.s

# target to generate assembly for a file
src/ZergUnit.cpp.s:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/ZergUnit.cpp.s
.PHONY : src/ZergUnit.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/starcraft.dir/build.make CMakeFiles/starcraft.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... starcraft"
	@echo "... edit_cache"
	@echo "... src/Building.o"
	@echo "... src/Building.i"
	@echo "... src/Building.s"
	@echo "... src/BuildlistValidator.o"
	@echo "... src/BuildlistValidator.i"
	@echo "... src/BuildlistValidator.s"
	@echo "... src/CSVParser.o"
	@echo "... src/CSVParser.i"
	@echo "... src/CSVParser.s"
	@echo "... src/Entity.o"
	@echo "... src/Entity.i"
	@echo "... src/Entity.s"
	@echo "... src/EntityData.o"
	@echo "... src/EntityData.i"
	@echo "... src/EntityData.s"
	@echo "... src/FixedPoint.o"
	@echo "... src/FixedPoint.i"
	@echo "... src/FixedPoint.s"
	@echo "... src/JsonLogger.o"
	@echo "... src/JsonLogger.i"
	@echo "... src/JsonLogger.s"
	@echo "... src/JsonLoggerV2.o"
	@echo "... src/JsonLoggerV2.i"
	@echo "... src/JsonLoggerV2.s"
	@echo "... src/ProtossBuilding.o"
	@echo "... src/ProtossBuilding.i"
	@echo "... src/ProtossBuilding.s"
	@echo "... src/ProtossSimulator.o"
	@echo "... src/ProtossSimulator.i"
	@echo "... src/ProtossSimulator.s"
	@echo "... src/ProtossUnit.o"
	@echo "... src/ProtossUnit.i"
	@echo "... src/ProtossUnit.s"
	@echo "... src/ResourceManager.o"
	@echo "... src/ResourceManager.i"
	@echo "... src/ResourceManager.s"
	@echo "... src/Tech.o"
	@echo "... src/Tech.i"
	@echo "... src/Tech.s"
	@echo "... src/TerranBuilding.o"
	@echo "... src/TerranBuilding.i"
	@echo "... src/TerranBuilding.s"
	@echo "... src/TerranSimulator.o"
	@echo "... src/TerranSimulator.i"
	@echo "... src/TerranSimulator.s"
	@echo "... src/TerranUnit.o"
	@echo "... src/TerranUnit.i"
	@echo "... src/TerranUnit.s"
	@echo "... src/Timer.o"
	@echo "... src/Timer.i"
	@echo "... src/Timer.s"
	@echo "... src/Unit.o"
	@echo "... src/Unit.i"
	@echo "... src/Unit.s"
	@echo "... src/ZergBuilding.o"
	@echo "... src/ZergBuilding.i"
	@echo "... src/ZergBuilding.s"
	@echo "... src/ZergSimulator.o"
	@echo "... src/ZergSimulator.i"
	@echo "... src/ZergSimulator.s"
	@echo "... src/ZergUnit.o"
	@echo "... src/ZergUnit.i"
	@echo "... src/ZergUnit.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

